services:
  app:
    build: .
    image: wareniex_app:hd
    container_name: wareniex_app
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: public.ecr.aws/docker/library/mongo:7
    container_name: wareniex_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "localhost:27017/Wareniex",
          "--eval",
          "db.runCommand({ ping: 1 }).ok",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mongo_data:
